import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/footer";
import Header from "@/components/Header";

const monsrat = Montserrat({ subsets: ["latin"], weight :'700' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monsrat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
